# Generated by Django 3.2.4 on 2021-06-11 03:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mídia')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Quantidade')),
                ('year_release', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Ano de Lançamento')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game', verbose_name='Jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Mídia')),
                ('Velocidade de Leitura', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Plataforma')),
                ('year_release', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Ano de Lançamento')),
                ('memory', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Memória')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nome')),
                ('year_fundation', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Ano da Fundação')),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddField(
            model_name='platform',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producer', verbose_name='Produtora'),
        ),
        migrations.AddField(
            model_name='game_platform',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.platform', verbose_name='Plataforma'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(through='core.Game_Platform', to='core.Platform', verbose_name='Plataforma'),
        ),
    ]
