# Generated by Django 3.2.4 on 2021-06-11 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210611_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.media', verbose_name='Mídia'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Jogo'),
        ),
    ]
