# Generated by Django 3.2.4 on 2021-06-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210611_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='media',
        ),
        migrations.AddField(
            model_name='platform',
            name='media',
            field=models.ManyToManyField(to='core.Media', verbose_name='Mídia'),
        ),
    ]
